[workspace]

members = [
  "check-specifications",
  "libpeercast-re",
  "peercast-re",
  "peercast-root",
  "peercast-utils",
]
default-members = ["libpeercast-re", "peercast-root", "peercast-re", "peercast-utils"]

resolver = "2"
