[workspace]

members = [
    "check-specifications",
    "peercast-re",
    "peercast-root",
    "peercast-utils",
    "peercast-speedtest",
    "packages/peercast-atom",
    "packages/peercast-id4",
    "packages/peercast-gnuid",
    "packages/old-libpeercast-re",
    "packages/libpeercast-renew",
]
default-members = [
    "packages/old-libpeercast-re",
    "packages/libpeercast-renew",
    "peercast-root",
    "peercast-re",
    "peercast-utils",
    "peercast-speedtest",
]

resolver = "2"
