[workspace]

members = [
  "check-specifications",
  "libpeercast-re",
  "peercast-re",
  "peercast-root",
  "peercast-utils",
  "peercast-speedtest", "packages/peercast-atom",
]
default-members = ["libpeercast-re", "peercast-root", "peercast-re", "peercast-utils", "peercast-speedtest", "packages/peercast-atom"]

resolver = "2"
