version: "3"
services:
  plantuml-server:
    image: plantuml/plantuml-server:jetty
    # image: plantuml/plantuml-server:tomcat
    restart: always
    ports:
      - "18080:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
