version: "3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    # container_name: "swagger-editor"
    ports:
      - "8001:8080"
    volumes:
      - ./api:/api # Swagger Directory
    environment:
      SWAGGER_FILE: /api/openapi.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    # container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api:/api # Swagger File
    environment:
      SWAGGER_JSON: /api/openapi.yaml # Swagger File


  # swagger-api:
  #   image: stoplight/prism:latest
  #   # container_name: "swagger-api"
  #   ports:
  #     - "8003:4010"
  #   command: mock -h 0.0.0.0 /api/openapi.yaml # Swagger File
  #   volumes:
  #     - ./api:/api # Swagger File
