# --------------------------------------------------------------------------------
# for Server
#
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean", "client-build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.run]
command = "cargo"
args = ["run"]

# --------------------------------------------------------------------------------
# for Client
#
[tasks.client-build]
script = "cd client; npm run build"

[tasks.client-dev]
script = "cd client; npm run dev"

# --------------------------------------------------------------------------------
# Both
#
[tasks.dev]
run_task = { name = ["run", "client-dev"], fork = true, parallel = true }
dependencies = ["client-build"]
