#tab_spaces = 4

# 最大幅、行のコード幅をこの幅以内に収めようとする
max_width = 120

# max_widthの値をもとに他の*_widthの値を算出する
# https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=width#use_small_heuristics
#use_small_heuristics = "Default"
use_small_heuristics = "Off"
# use_small_heuristics = "Max"

# fn_call_width=200
# attr_fn_like_width=200
# struct_lit_width=200
# struct_variant_width=200
# array_width=200
# chain_width=200
# single_line_if_else_max_width=200
# single_line_let_else_max_width=200
