FROM ubuntu:noble

WORKDIR /app

ARG TARGET=.
ARG PROFILE=release

# default(no build-arg) ./target/release/peercast-root
COPY --chmod=755 ./target/${TARGET}/${PROFILE}/peercast-root      /app
COPY --chmod=644 ./peercast-root/share/peercast-root_footer.toml  /app

EXPOSE 7144 7143

ENTRYPOINT [ "/app/peercast-root" ]
#CMD ["/app/peercast-root"]
