FROM ubuntu:noble

WORKDIR /app

ARG TARGET=.
ARG PROFILE=release

# default(no build-arg) ./target/release/peercast-root
COPY ./target/${TARGET}/${PROFILE}/peercast-root /app

EXPOSE 7144 7143

CMD ["/app/peercast-root"]
