# デフォルトの設定でtarget.TARGET_SYSTEMを上書きしている、排他的な設定
# [build]
# rustflags = [
#   "--cfg", "tokio_unstable"
# ]

[target.x86_64-unknown-linux-gnu]
# linker = "clang"
rustflags = [
  # for tokio-console
  "--cfg", "tokio_unstable",

  # LLD linker
  #
  # You may need to install it:
  #
  # - Ubuntu: `sudo apt-get install lld clang`
  # - Fedora: `sudo dnf install lld clang`
  # - Arch: `sudo pacman -S lld clang`
  # "-Clink-arg=-fuse-ld=lld",

  # Mold linker
  #
  # You may need to install it:
  #
  # - Ubuntu: `sudo apt-get install mold clang`
  # - Fedora: `sudo dnf install mold clang`
  # - Arch: `sudo pacman -S mold clang`
  "-Clink-arg=-fuse-ld=mold",

  # Nightly
  # "-Zshare-generics=y",
  # "-Zthreads=0",

]

rustdocflags = [
  # LLD linker
  # "-Clink-arg=-fuse-ld=lld",

  # Mold linker
  "-Clink-arg=-fuse-ld=mold",
]
