#!/bin/sh

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask peercast-root.service >/dev/null
		deb-systemd-helper mask peercast-port-checkerd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper unmask peercast-root.service >/dev/null

		deb-systemd-helper unmask peercast-port-checkerd.service >/dev/null
	fi
fi
