name: cleanup caches by a branch
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: deleted branch-name
        required: true
        type: string
      limit_num:
        description: max delete cache count
        required: false
        type: number
        default: 1000

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      BRANCH: "refs/heads/${{ inputs.branch_name }}"
      LIMIT_NUM: "${{ inputs.limit_num }}"
    steps:
      - name: Cleanup
        shell: bash
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit $LIMIT_NUM --json id --jq '.[].id' | awk '{print NR,$0}')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          i=0
          for cacheKey in $cacheKeysForPR
          do
              echo delete $i
              gh cache delete $cacheKey
              # bash's increment
              ((count++))
          done
          echo "Done"
        # if: startsWith(github.event.ref, 'feature/')
        # env:
          # pull request
          # BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
          # branch
          # BRANCH: refs/heads/${{ github.event.ref }}
