name: Delete workflow

on:
  # これのイベントはデフォルトブランチ(多くの場合、main)上にワークフローファイルがあるときのみ利用できる
  workflow_dispatch:
    inputs:
      workflow:
        description: workflow-id, workflow-name or filename
        required: true
        type: string

jobs:
  delete:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WORKFLOW: ${{ github.event.inputs.workflow }}
    # SEE permission settings:
    # https://docs.github.com/ja/rest/actions/workflow-runs?apiVersion=2022-11-28#delete-a-workflow-run
    permissions:
      actions: write

    steps:
      - uses: actions/checkout@v4

      - run: gh workflow view "${WORKFLOW}"
      - name: Execute
        env:
            REPOSITORY: ${{ github.repository }}
        # 4並列で実行するのはどうかなー
        run: |
          echo repo: ${REPOSITORY}
          echo WORKFLOW: ${WORKFLOW}
          gh run list --workflow "${WORKFLOW}" --limit 1000 --json databaseId,status --jq '.[] | select(.status == "completed") | .databaseId' \
            | xargs -P 4 -I {} gh api -X DELETE repos/${REPOSITORY}/actions/runs/{}
